# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Absolute Testicle Blast

# on:
#   push:
#     branches: [ main ]
on:
  schedule:
  - cron: "* * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shit
      run: node index.js
