# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Absolute Testicle Blast

# on:
#   push:
#     branches: [ main ]
on:
  push:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  Absolute-Testicle-Blast:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Tacos
      run: |
        npm ci
        node src/index.js
